variables:
  GO_PACKAGE:    github.com/wikiwi/kube-volume-freezer
  REPOSITORY:    registry.intra.wikiwi.io/vinh/kube-volume-freezer
  DOCKER_HOST:   tcp://wikiwi__dind:2375
  MASTER_BRANCH: origin/master

stages:
  - test-and-build
  - registry

test-and-build:
  stage: test-and-build
  image: golang:1.6
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
  cache:
    paths:
      - vendor
  before_script:
    - make info
    - mkdir -p /go/src/$(dirname ${GO_PACKAGE})
    - ln -s $(pwd) /go/src/${GO_PACKAGE}
    - cd /go/src/${GO_PACKAGE} && make bootstrap
  script:
    - cd /go/src/${GO_PACKAGE} && make test build-for-docker

push-image-to-registry:
  stage: registry
  image: wikiwi/docker-build:canary
  services:
    - wikiwi/dind
  only:
    - master
  tags:
    - sequential
  before_script:
    - make info
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.intra.wikiwi.io
  script:
    - make docker-build docker-push

