apiVersion: v1
kind: Service
metadata:
  name: kube-volume-freezer
  labels:
    app: kube-volume-freezer
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kube-volume-freezer
    component: master

